basePath: /v1
definitions:
  common.ErrResp:
    properties:
      code:
        type: string
      errors:
        type: object
      message:
        type: string
    type: object
  common.RegisterForm:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - password
    - email
    type: object
  model.Book:
    properties:
      author_id:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      price:
        type: number
      title:
        type: string
      updated_at:
        type: string
    type: object
  model.Token:
    properties:
      created_at:
        type: string
      id:
        type: integer
      token:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  model.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is our backend api server.
  license:
    name: MIT
  title: Backend API
  version: "0.1"
paths:
  /books:
    get:
      consumes:
      - application/json
      parameters:
      - default: 100
        description: limit
        in: query
        name: limit
        type: integer
      - default: 0
        description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
        "500":
          description: StatusInternalServerError
      summary: Books pagination query all
  /books/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Book id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
            type: object
        "500":
          description: StatusInternalServerError
      summary: Books query by id
  /me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
            type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.ErrResp'
            type: object
        "500":
          description: StatusInternalServerError
      security:
      - ApiKeyAuth: []
      summary: Me message
  /p:
    get:
      consumes:
      - application/json
      parameters:
      - default: 100
        description: limit
        in: query
        name: limit
        type: integer
      - default: 0
        description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "500":
          description: StatusInternalServerError
      summary: Test pagination
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Register user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/common.RegisterForm'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Token'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrResp'
            type: object
        "500":
          description: StatusInternalServerError
      summary: Register a new user
  /users/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
            type: object
        "500":
          description: StatusInternalServerError
      summary: Users query by id
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
